package entity;
// Generated 18/06/2018 11:42:53 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Set inscripcions = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(int id, String descripcion) {
        this.id = id;
        this.descripcion = descripcion;
    }
    public Categoria(int id, String descripcion, Set inscripcions) {
       this.id = id;
       this.descripcion = descripcion;
       this.inscripcions = inscripcions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getInscripcions() {
        return this.inscripcions;
    }
    
    public void setInscripcions(Set inscripcions) {
        this.inscripcions = inscripcions;
    }
    
    @Override
    public String toString() {
        return descripcion;
    }




}


