package entity;
// Generated 18/06/2018 11:42:53 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Competidor generated by hbm2java
 */
public class Competidor  implements java.io.Serializable {


     private int dni;
     private Escuela escuela;
     private String nombre;
     private String apellido;
     private String direccion;
     private String sexo;
     private Date fechaNac;
     private Set inscripcions = new HashSet(0);

    public Competidor() {
    }

	
    public Competidor(int dni, Escuela escuela, String nombre, String apellido, String direccion, String sexo, Date fechaNac) {
        this.dni = dni;
        this.escuela = escuela;
        this.nombre = nombre;
        this.apellido = apellido;
        this.direccion = direccion;
        this.sexo = sexo;
        this.fechaNac = fechaNac;
    }
    public Competidor(int dni, Escuela escuela, String nombre, String apellido, String direccion, String sexo, Date fechaNac, Set inscripcions) {
       this.dni = dni;
       this.escuela = escuela;
       this.nombre = nombre;
       this.apellido = apellido;
       this.direccion = direccion;
       this.sexo = sexo;
       this.fechaNac = fechaNac;
       this.inscripcions = inscripcions;
    }
   
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }
    public Escuela getEscuela() {
        return this.escuela;
    }
    
    public void setEscuela(Escuela escuela) {
        this.escuela = escuela;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public Set getInscripcions() {
        return this.inscripcions;
    }
    
    public void setInscripcions(Set inscripcions) {
        this.inscripcions = inscripcions;
    }


    @Override
    public String toString() {
        return nombre + " " + apellido;
    }


}


