package entity;
// Generated 18/06/2018 11:42:53 by Hibernate Tools 4.3.1



/**
 * InscripcionId generated by hbm2java
 */
public class InscripcionId  implements java.io.Serializable {


     private int dniCompetidor;
     private int idDisciplina;
     private int idCategoria;

    public InscripcionId() {
    }

    public InscripcionId(int dniCompetidor, int idDisciplina, int idCategoria) {
       this.dniCompetidor = dniCompetidor;
       this.idDisciplina = idDisciplina;
       this.idCategoria = idCategoria;
    }
   
    public int getDniCompetidor() {
        return this.dniCompetidor;
    }
    
    public void setDniCompetidor(int dniCompetidor) {
        this.dniCompetidor = dniCompetidor;
    }
    public int getIdDisciplina() {
        return this.idDisciplina;
    }
    
    public void setIdDisciplina(int idDisciplina) {
        this.idDisciplina = idDisciplina;
    }
    public int getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(int idCategoria) {
        this.idCategoria = idCategoria;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InscripcionId) ) return false;
		 InscripcionId castOther = ( InscripcionId ) other; 
         
		 return (this.getDniCompetidor()==castOther.getDniCompetidor())
 && (this.getIdDisciplina()==castOther.getIdDisciplina())
 && (this.getIdCategoria()==castOther.getIdCategoria());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getDniCompetidor();
         result = 37 * result + this.getIdDisciplina();
         result = 37 * result + this.getIdCategoria();
         return result;
   }   


}


