package entity;
// Generated 18/06/2018 11:42:53 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Torneo generated by hbm2java
 */
public class Torneo  implements java.io.Serializable {


     private int id;
     private Date fecha;
     private String sede;
     private Set inscripcions = new HashSet(0);

    public Torneo() {
    }

    public Torneo(int id) {
        this.id = id;
    }
	
    public Torneo(int id, Date fecha, String sede) {
        this.id = id;
        this.fecha = fecha;
        this.sede = sede;
    }
    public Torneo(int id, Date fecha, String sede, Set inscripcions) {
       this.id = id;
       this.fecha = fecha;
       this.sede = sede;
       this.inscripcions = inscripcions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getSede() {
        return this.sede;
    }
    
    public void setSede(String sede) {
        this.sede = sede;
    }
    public Set getInscripcions() {
        return this.inscripcions;
    }
    
    public void setInscripcions(Set inscripcions) {
        this.inscripcions = inscripcions;
    }




}


